apiVersion: apps/v1
kind: Deployment
metadata:
  name: obj-det-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: obj-det-app
  template:
    metadata:
      labels:
        app: obj-det-app
    spec:
      containers:
      - name: obj-det-app
        image: digitalvillage132da3e8.azurecr.io/object-detection:latest
        ports:
        - containerPort: 8000
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: obj-det-app-svc
spec:
  selector:
    app: obj-det-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
