version: "3.8"

services:
  fastapi-detr:
    build:
      context: .
    image: digitalvillage132da3e8.azurecr.io/object-detection:latest
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]